spring.application.name=backend

# Configuração do Banco de Dados MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/vipstyle_db
spring.datasource.username=root
spring.datasource.password=Du44xdoda@

# Configuração do JPA (para criar/atualizar a tabela 'produtos' automaticamente)
spring.jpa.hibernate.ddl-auto=update

server.port=8080
